version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - \\wsl.localhost\Ubuntu\var\lib\postgresql\14
      
  web:
    build: .
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pgdata: