version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_URL: ${DATABASE_URL}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    volumes:
      - /mnt/wsl/var/lib/postgresql/14/main:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
  web:
    build: .
    command: flask run
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

# volumes:
#   postgres_data: